packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^24
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
  vue: ^3.5.34
  vue-router: ^5.0.7
  modern-monaco: ^0.4.1
  "@vitejs/plugin-vue": ^6.0.7
  unplugin-vue-router: ^0.19.2
  unplugin-auto-import: ^21.0.0
  unplugin-vue-components: ^32.1.0
  unocss: ^66.7.0
  "@unocss/vite": ^66.7.0
  "@unocss/reset": ^66.7.0
  bumpp: ^11.1.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
