packages:
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  '@types/node': ^25.9.1
  typescript: ^6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
  '@typescript/native-preview': 7.0.0-dev.20260509.2
  bumpp: ^11.1.0

overrides:
  vite: 'catalog:'
  vitest: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'

minimumReleaseAgeExclude:
  - '@yyds-lang/textmate'
