export const YYDS_DIAGNOSTIC_CODES = {
  LEX_UNTERMINATED_STRING: "YYDS_LEX_UNTERMINATED_STRING",
  PARSE_UNEXPECTED_TOKEN: "YYDS_PARSE_UNEXPECTED_TOKEN",
  SEM_DUPLICATE_SECTION: "YYDS_SEM_DUPLICATE_SECTION",
  SEM_UNKNOWN_SECTION: "YYDS_SEM_UNKNOWN_SECTION",
  SEM_UNKNOWN_TRACK: "YYDS_SEM_UNKNOWN_TRACK",
  SEM_CYCLIC_REF: "YYDS_SEM_CYCLIC_REF",
} as const;

export type YydsDiagnosticCode = (typeof YYDS_DIAGNOSTIC_CODES)[keyof typeof YYDS_DIAGNOSTIC_CODES];

export const YYDS_DIAGNOSTIC_SEVERITY = {
  ERROR: "error",
  WARNING: "warning",
  INFO: "info",
} as const;
